# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cab78bdd33cd25eb0d659d9d5d9e3906961889925f47f11e96f54e311051658976ec4eddcabdc73928ea1d91e95ce86a0d0a4b272b527a113cb8ae7b59168331

test:
  secret_key_base: 6b91c6b7e14165aae9093aad0e94f37fc295be9ac969008111b3ad980386a855824d722ce206a8ab6050761725b71898897b2f379fe42578438cfed619e638f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
